"""add match_rule_sets.field_map

Hand-written (not autogenerated — autogenerate emits spurious
cross-schema FK recreations against SQLite on this setup): one nullable
JSON column on the app-schema match_rule_sets table holding the
per-customer FieldMapping (which gold columns drive the match signals).
NULL means historical defaults. Plain ADD COLUMN — no batch mode needed.

Revision ID: 2a94c1e07f31
Revises: 17b3bbe9ec08
Create Date: 2026-08-24

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a94c1e07f31'
down_revision: Union[str, None] = '17b3bbe9ec08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('match_rule_sets', sa.Column(
        'field_map',
        sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()),
                               'postgresql'),
        nullable=True))


def downgrade() -> None:
    op.drop_column('match_rule_sets', 'field_map')
