"""initial schema (medallion split)

Revision ID: bfc9078a3cc6
Revises: 
Create Date: 2026-08-24 11:53:19.383060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bfc9078a3cc6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # SQLite fakes schemas via ATTACH DATABASE (db.base.register_sqlite_attach);
    # real schemas need to exist before CREATE TABLE targets them on Postgres.
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute(sa.text("CREATE SCHEMA IF NOT EXISTS bronze"))
        op.execute(sa.text("CREATE SCHEMA IF NOT EXISTS silver"))
        op.execute(sa.text("CREATE SCHEMA IF NOT EXISTS gold"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_key'), ['key'], unique=True)

    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('adapter_key', sa.String(length=64), nullable=True),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=500), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'sha256'),
    schema='bronze'
    )
    with op.batch_alter_table('files', schema='bronze') as batch_op:
        batch_op.create_index(batch_op.f('ix_bronze_files_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bronze_files_sha256'), ['sha256'], unique=False)

    op.create_table('match_rule_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('date_tolerance_days', sa.Integer(), nullable=False),
    sa.Column('amount_tolerance', sa.Float(), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('co7_lookback_days', sa.Integer(), nullable=False),
    sa.Column('allow_batched', sa.Boolean(), nullable=False),
    sa.Column('max_batch_size', sa.Integer(), nullable=False),
    sa.Column('paid_statuses', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('weights', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_rule_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_rule_sets_customer_id'), ['customer_id'], unique=False)

    op.create_table('source_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('adapter_key', sa.String(length=64), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'source_type')
    )
    with op.batch_alter_table('source_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_configs_customer_id'), ['customer_id'], unique=False)

    op.create_table('runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('rule_set_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('selfcheck', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('workbook_path', sa.String(length=500), nullable=True),
    sa.Column('error', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['rule_set_id'], ['match_rule_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index('uq_runs_one_running_per_customer', ['customer_id'], unique=True, sqlite_where=sa.text("status = 'running'"), postgresql_where=sa.text("status = 'running'"))

    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bronze_file_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('frame_name', sa.String(length=64), nullable=False),
    sa.Column('row_seq', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['bronze_file_id'], ['bronze.files.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='silver'
    )
    with op.batch_alter_table('records', schema='silver') as batch_op:
        batch_op.create_index(batch_op.f('ix_silver_records_bronze_file_id'), ['bronze_file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_silver_records_customer_id'), ['customer_id'], unique=False)

    op.create_table('bank_txns',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('bronze_file_id', sa.Integer(), nullable=False),
    sa.Column('row_seq', sa.Integer(), nullable=False),
    sa.Column('bank_ref', sa.String(length=64), nullable=True),
    sa.Column('customer_ref', sa.String(length=64), nullable=True),
    sa.Column('txn_type', sa.String(length=16), nullable=True),
    sa.Column('supplementary', sa.String(length=64), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('txn_timestamp', sa.String(length=64), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('zone_guess', sa.String(length=16), nullable=True),
    sa.Column('used_in_recon', sa.Boolean(), nullable=False),
    sa.Column('extras', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['bronze_file_id'], ['bronze.files.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bronze_file_id', 'row_seq', 'run_id'),
    schema='gold'
    )
    with op.batch_alter_table('bank_txns', schema='gold') as batch_op:
        batch_op.create_index(batch_op.f('ix_gold_bank_txns_bronze_file_id'), ['bronze_file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gold_bank_txns_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gold_bank_txns_run_id'), ['run_id'], unique=False)
        batch_op.create_index('uq_bank_txns_file_seq', ['bronze_file_id', 'row_seq'], unique=True)

    op.create_table('bills',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('bronze_file_id', sa.Integer(), nullable=False),
    sa.Column('row_seq', sa.Integer(), nullable=False),
    sa.Column('bill_number', sa.String(length=100), nullable=True),
    sa.Column('contract_no', sa.String(length=100), nullable=True),
    sa.Column('contract_date', sa.Date(), nullable=True),
    sa.Column('bill_date', sa.Date(), nullable=True),
    sa.Column('zone', sa.String(length=16), nullable=True),
    sa.Column('party_name', sa.String(length=200), nullable=True),
    sa.Column('party_code', sa.String(length=64), nullable=True),
    sa.Column('payment_advice_date', sa.Date(), nullable=True),
    sa.Column('accounting_unit', sa.String(length=100), nullable=True),
    sa.Column('co6_no', sa.String(length=64), nullable=True),
    sa.Column('co6_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('bill_amt', sa.Float(), nullable=True),
    sa.Column('passed_amt', sa.Float(), nullable=True),
    sa.Column('deducted_amt', sa.Float(), nullable=True),
    sa.Column('net_amt', sa.Float(), nullable=True),
    sa.Column('co7_no', sa.String(length=64), nullable=True),
    sa.Column('co7_date', sa.Date(), nullable=True),
    sa.Column('recovery_count', sa.Integer(), nullable=True),
    sa.Column('reason_for_return', sa.Text(), nullable=True),
    sa.Column('recovery_sum', sa.Float(), nullable=True),
    sa.Column('net_check', sa.Boolean(), nullable=True),
    sa.Column('recovery_check', sa.Boolean(), nullable=True),
    sa.Column('sheet', sa.String(length=64), nullable=True),
    sa.Column('header_row', sa.Integer(), nullable=True),
    sa.Column('data_row', sa.Integer(), nullable=True),
    sa.Column('extras', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['bronze_file_id'], ['bronze.files.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bronze_file_id', 'row_seq', 'run_id'),
    schema='gold'
    )
    with op.batch_alter_table('bills', schema='gold') as batch_op:
        batch_op.create_index(batch_op.f('ix_gold_bills_bill_number'), ['bill_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_gold_bills_bronze_file_id'), ['bronze_file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gold_bills_co6_no'), ['co6_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_gold_bills_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gold_bills_run_id'), ['run_id'], unique=False)
        batch_op.create_index('uq_bills_file_seq', ['bronze_file_id', 'row_seq'], unique=True)

    op.create_table('lineage_docs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('bronze_file_id', sa.Integer(), nullable=False),
    sa.Column('row_seq', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=8), nullable=False),
    sa.Column('doc_no', sa.String(length=100), nullable=True),
    sa.Column('doc_date', sa.Date(), nullable=True),
    sa.Column('invoice_no', sa.String(length=100), nullable=True),
    sa.Column('co6_no', sa.String(length=64), nullable=True),
    sa.Column('co7_no', sa.String(length=64), nullable=True),
    sa.Column('po_no', sa.String(length=100), nullable=True),
    sa.Column('po_date', sa.Date(), nullable=True),
    sa.Column('receipt_qty', sa.String(length=64), nullable=True),
    sa.Column('drr_or_challan_no', sa.String(length=100), nullable=True),
    sa.Column('bill_reg_no', sa.String(length=100), nullable=True),
    sa.Column('extras', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['bronze_file_id'], ['bronze.files.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bronze_file_id', 'row_seq', 'run_id'),
    schema='gold'
    )
    with op.batch_alter_table('lineage_docs', schema='gold') as batch_op:
        batch_op.create_index(batch_op.f('ix_gold_lineage_docs_bronze_file_id'), ['bronze_file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gold_lineage_docs_co6_no'), ['co6_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_gold_lineage_docs_co7_no'), ['co7_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_gold_lineage_docs_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gold_lineage_docs_doc_no'), ['doc_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_gold_lineage_docs_invoice_no'), ['invoice_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_gold_lineage_docs_run_id'), ['run_id'], unique=False)
        batch_op.create_index('uq_lineage_docs_file_seq', ['bronze_file_id', 'row_seq'], unique=True)

    op.create_table('run_frames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('rows', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'name')
    )
    with op.batch_alter_table('run_frames', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_frames_run_id'), ['run_id'], unique=False)

    op.create_table('exception_ledger',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('exception_type', sa.String(length=16), nullable=False),
    sa.Column('gold_bank_txn_id', sa.String(length=32), nullable=True),
    sa.Column('gold_bill_id', sa.String(length=32), nullable=True),
    sa.Column('first_seen_run_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('resolved_by_run_id', sa.String(length=32), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['first_seen_run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['gold_bank_txn_id'], ['gold.bank_txns.id'], ),
    sa.ForeignKeyConstraint(['gold_bill_id'], ['gold.bills.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exception_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exception_ledger_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exception_ledger_gold_bank_txn_id'), ['gold_bank_txn_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exception_ledger_gold_bill_id'), ['gold_bill_id'], unique=False)

    op.create_table('recoveries',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('bronze_file_id', sa.Integer(), nullable=False),
    sa.Column('row_seq', sa.Integer(), nullable=False),
    sa.Column('gold_bill_id', sa.String(length=32), nullable=True),
    sa.Column('bill_number', sa.String(length=100), nullable=True),
    sa.Column('co6_no', sa.String(length=64), nullable=True),
    sa.Column('sheet', sa.String(length=64), nullable=True),
    sa.Column('recovery_head', sa.String(length=200), nullable=True),
    sa.Column('recovery_amt', sa.Float(), nullable=True),
    sa.Column('recovery_text', sa.Text(), nullable=True),
    sa.Column('extras', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['bronze_file_id'], ['bronze.files.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['gold_bill_id'], ['gold.bills.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bronze_file_id', 'row_seq', 'run_id'),
    schema='gold'
    )
    with op.batch_alter_table('recoveries', schema='gold') as batch_op:
        batch_op.create_index(batch_op.f('ix_gold_recoveries_bronze_file_id'), ['bronze_file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gold_recoveries_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gold_recoveries_gold_bill_id'), ['gold_bill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gold_recoveries_run_id'), ['run_id'], unique=False)
        batch_op.create_index('uq_recoveries_file_seq', ['bronze_file_id', 'row_seq'], unique=True)

    op.create_table('ingest_conflicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('gold_bill_id', sa.String(length=32), nullable=False),
    sa.Column('bronze_file_id', sa.Integer(), nullable=False),
    sa.Column('changed_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bronze_file_id'], ['bronze.files.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['gold_bill_id'], ['gold.bills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingest_conflicts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingest_conflicts_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingest_conflicts_gold_bill_id'), ['gold_bill_id'], unique=False)

    op.create_table('match_ledger',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('match_id', sa.String(length=16), nullable=False),
    sa.Column('gold_bank_txn_id', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('locked_by', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['gold_bank_txn_id'], ['gold.bank_txns.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_ledger_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_ledger_gold_bank_txn_id'), ['gold_bank_txn_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_ledger_run_id'), ['run_id'], unique=False)

    op.create_table('run_match_bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('match_id', sa.String(length=16), nullable=False),
    sa.Column('gold_bill_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['gold_bill_id'], ['gold.bills.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_match_bills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_match_bills_gold_bill_id'), ['gold_bill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_match_bills_run_id'), ['run_id'], unique=False)

    op.create_table('match_ledger_bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_ledger_id', sa.String(length=32), nullable=False),
    sa.Column('gold_bill_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['gold_bill_id'], ['gold.bills.id'], ),
    sa.ForeignKeyConstraint(['match_ledger_id'], ['match_ledger.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_ledger_bills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_ledger_bills_gold_bill_id'), ['gold_bill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_ledger_bills_match_ledger_id'), ['match_ledger_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_ledger_bills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_ledger_bills_match_ledger_id'))
        batch_op.drop_index(batch_op.f('ix_match_ledger_bills_gold_bill_id'))

    op.drop_table('match_ledger_bills')
    with op.batch_alter_table('run_match_bills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_match_bills_run_id'))
        batch_op.drop_index(batch_op.f('ix_run_match_bills_gold_bill_id'))

    op.drop_table('run_match_bills')
    with op.batch_alter_table('match_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_ledger_run_id'))
        batch_op.drop_index(batch_op.f('ix_match_ledger_gold_bank_txn_id'))
        batch_op.drop_index(batch_op.f('ix_match_ledger_customer_id'))

    op.drop_table('match_ledger')
    with op.batch_alter_table('ingest_conflicts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingest_conflicts_gold_bill_id'))
        batch_op.drop_index(batch_op.f('ix_ingest_conflicts_customer_id'))

    op.drop_table('ingest_conflicts')
    with op.batch_alter_table('recoveries', schema='gold') as batch_op:
        batch_op.drop_index('uq_recoveries_file_seq')
        batch_op.drop_index(batch_op.f('ix_gold_recoveries_run_id'))
        batch_op.drop_index(batch_op.f('ix_gold_recoveries_gold_bill_id'))
        batch_op.drop_index(batch_op.f('ix_gold_recoveries_customer_id'))
        batch_op.drop_index(batch_op.f('ix_gold_recoveries_bronze_file_id'))

    op.drop_table('recoveries', schema='gold')
    with op.batch_alter_table('exception_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exception_ledger_gold_bill_id'))
        batch_op.drop_index(batch_op.f('ix_exception_ledger_gold_bank_txn_id'))
        batch_op.drop_index(batch_op.f('ix_exception_ledger_customer_id'))

    op.drop_table('exception_ledger')
    with op.batch_alter_table('run_frames', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_frames_run_id'))

    op.drop_table('run_frames')
    with op.batch_alter_table('lineage_docs', schema='gold') as batch_op:
        batch_op.drop_index('uq_lineage_docs_file_seq')
        batch_op.drop_index(batch_op.f('ix_gold_lineage_docs_run_id'))
        batch_op.drop_index(batch_op.f('ix_gold_lineage_docs_invoice_no'))
        batch_op.drop_index(batch_op.f('ix_gold_lineage_docs_doc_no'))
        batch_op.drop_index(batch_op.f('ix_gold_lineage_docs_customer_id'))
        batch_op.drop_index(batch_op.f('ix_gold_lineage_docs_co7_no'))
        batch_op.drop_index(batch_op.f('ix_gold_lineage_docs_co6_no'))
        batch_op.drop_index(batch_op.f('ix_gold_lineage_docs_bronze_file_id'))

    op.drop_table('lineage_docs', schema='gold')
    with op.batch_alter_table('bills', schema='gold') as batch_op:
        batch_op.drop_index('uq_bills_file_seq')
        batch_op.drop_index(batch_op.f('ix_gold_bills_run_id'))
        batch_op.drop_index(batch_op.f('ix_gold_bills_customer_id'))
        batch_op.drop_index(batch_op.f('ix_gold_bills_co6_no'))
        batch_op.drop_index(batch_op.f('ix_gold_bills_bronze_file_id'))
        batch_op.drop_index(batch_op.f('ix_gold_bills_bill_number'))

    op.drop_table('bills', schema='gold')
    with op.batch_alter_table('bank_txns', schema='gold') as batch_op:
        batch_op.drop_index('uq_bank_txns_file_seq')
        batch_op.drop_index(batch_op.f('ix_gold_bank_txns_run_id'))
        batch_op.drop_index(batch_op.f('ix_gold_bank_txns_customer_id'))
        batch_op.drop_index(batch_op.f('ix_gold_bank_txns_bronze_file_id'))

    op.drop_table('bank_txns', schema='gold')
    with op.batch_alter_table('records', schema='silver') as batch_op:
        batch_op.drop_index(batch_op.f('ix_silver_records_customer_id'))
        batch_op.drop_index(batch_op.f('ix_silver_records_bronze_file_id'))

    op.drop_table('records', schema='silver')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index('uq_runs_one_running_per_customer', sqlite_where=sa.text("status = 'running'"), postgresql_where=sa.text("status = 'running'"))
        batch_op.drop_index(batch_op.f('ix_runs_customer_id'))

    op.drop_table('runs')
    with op.batch_alter_table('source_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_configs_customer_id'))

    op.drop_table('source_configs')
    with op.batch_alter_table('match_rule_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_rule_sets_customer_id'))

    op.drop_table('match_rule_sets')
    with op.batch_alter_table('files', schema='bronze') as batch_op:
        batch_op.drop_index(batch_op.f('ix_bronze_files_sha256'))
        batch_op.drop_index(batch_op.f('ix_bronze_files_customer_id'))

    op.drop_table('files', schema='bronze')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_key'))

    op.drop_table('customers')
    # ### end Alembic commands ###

    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute(sa.text("DROP SCHEMA IF EXISTS gold CASCADE"))
        op.execute(sa.text("DROP SCHEMA IF EXISTS silver CASCADE"))
        op.execute(sa.text("DROP SCHEMA IF EXISTS bronze CASCADE"))
