"""add users table (the login gate)

Purely additive: one new table in the default (app) schema, no change to
any existing one. A login is not a medallion-layer fact, so it does not
belong in bronze/silver/gold.

Written by hand rather than autogenerated, for the reason recorded in
CLAUDE.md and in f1c6b2d84a95: against SQLite, autogenerate also proposes
re-creating every cross-schema foreign key already declared in
db/models.py, which would batch-rebuild tables that are already correct.

No backfill and no data migration. An existing database comes up with an
empty users table, which means NOBODY can sign in until one is created —
deliberately: `python -m scripts.create_user` (or ADMIN_EMAIL /
ADMIN_PASSWORD at seed time) is an explicit act, and a default account
shipped in a migration would be a backdoor.

Revision ID: e6c12a7b940f
Revises: c3f8a1d27e64
Create Date: 2026-09-18 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'e6c12a7b940f'
down_revision: Union[str, None] = 'c3f8a1d27e64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=320), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False,
                  server_default=sa.true()),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('last_login_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('users') as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'],
                              unique=True)


def downgrade() -> None:
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
    op.drop_table('users')
