"""add gold.file_rows (which gold rows each ingested file reported)

Purely additive: one new table in the gold schema, no change to any
existing one. Gold rows are entity-upserted, so a later export that
re-reports an existing bill leaves no trace under its own bronze file —
this table records the (file -> gold row) sighting so "show me what I
just ingested" can answer.

Written by hand rather than autogenerated: against SQLite, autogenerate
also proposes re-creating every cross-schema foreign key already declared
in db/models.py (SQLite cannot enforce FKs across ATTACHed files, so a
fresh reflection never sees them) — expected noise that would trigger a
batch recreate-and-copy of tables that are already correct.

Existing rows need no backfill: a file ingested before this table has no
sightings, and db/gold.py reported_by_file falls back to bronze_file_id
ownership for exactly that case.

Revision ID: f1c6b2d84a95
Revises: d7e3f5a18c42
Create Date: 2026-09-04 12:10:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'f1c6b2d84a95'
down_revision: Union[str, None] = 'd7e3f5a18c42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'file_rows',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('customer_id', sa.Integer(), nullable=False),
        sa.Column('bronze_file_id', sa.Integer(), nullable=False),
        sa.Column('frame', sa.String(length=64), nullable=False),
        sa.Column('gold_row_id', sa.String(length=32), nullable=False),
        sa.Column('row_seq', sa.Integer(), nullable=False),
        sa.Column('seen_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['bronze_file_id'], ['bronze.files.id'], ),
        sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
        sa.PrimaryKeyConstraint('id'),
        schema='gold',
    )
    with op.batch_alter_table('file_rows', schema='gold') as batch_op:
        batch_op.create_index(batch_op.f('ix_gold_file_rows_bronze_file_id'),
                              ['bronze_file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gold_file_rows_customer_id'),
                              ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gold_file_rows_gold_row_id'),
                              ['gold_row_id'], unique=False)
        batch_op.create_index('uq_file_rows_file_frame_seq',
                              ['bronze_file_id', 'frame', 'row_seq'],
                              unique=True)


def downgrade() -> None:
    with op.batch_alter_table('file_rows', schema='gold') as batch_op:
        batch_op.drop_index('uq_file_rows_file_frame_seq')
        batch_op.drop_index(batch_op.f('ix_gold_file_rows_gold_row_id'))
        batch_op.drop_index(batch_op.f('ix_gold_file_rows_customer_id'))
        batch_op.drop_index(batch_op.f('ix_gold_file_rows_bronze_file_id'))

    op.drop_table('file_rows', schema='gold')
