/**
 * What a column means, shown as the header's tooltip wherever it appears
 * (DataTable on every Data page and run table, the Analyst queue, AR,
 * Audit trail, the candidate comparison). Keyed by the column's data key;
 * table headers that are not data columns (the ledger's "When", "Decision"
 * …) use a `ui:` key. One sentence each, enterprise-terse: what the value
 * is, and where it matters, how it is used. A column with no entry simply
 * shows no tooltip.
 */
export const COLUMN_HELP: Record<string, string> = {
  // --- bank statement ---------------------------------------------------
  used_in_recon: 'Credits are reconciled; debits are listed only.',
  txn_type: 'Transaction type as printed on the statement.',
  amount: 'Credit amount on the bank statement. A bill must carry the same net payable to match.',
  source: 'IREPS money or another receipt. Editable: an analyst decision overrides the automatic reading.',
  value_date: 'Date the bank credited the money.',
  zone_guess: 'Railway zone read from the narrative. A credit with no zone is treated as a non-IREPS receipt.',
  zone_from_narrative: 'Railway zone read from the bank narrative.',
  narrative: 'Free text the bank printed with the transaction.',
  bank_narrative: 'Free text the bank printed with the transaction.',
  bank_ref: 'Bank reference of the transaction.',
  customer_ref: 'Customer reference printed on the statement.',
  page: 'Statement page the transaction was read from.',
  credit_scope: 'Where the credit sits in the Command Center funnel: recognised, awaiting data, or another receipt.',

  // --- bills -----------------------------------------------------------
  bill_number: 'IREPS bill number.',
  contract_no: 'Contract the bill was raised against.',
  zone: 'Railway zone of the bill (or, for a credit, read from the narrative).',
  bill_zone: 'Railway zone of the bill.',
  bill_status: 'Current IREPS status of the bill. Only PAYMENT MADE bills can settle a credit.',
  bill_date: 'Date on the bill.',
  gross_amount: 'Bill value before deductions.',
  approved_amount: 'Amount the railway approved.',
  deduction_amount: 'Total deducted (recoveries, taxes, penalties).',
  net_payable_amount: 'Gross minus deductions: the amount the railway pays, and the amount a credit must equal to match.',
  submission_ref: 'CO6 number: the bill’s submission reference in IREPS.',
  submission_date: 'Date the bill was submitted (CO6).',
  payment_order_ref: 'CO7 number: the payment order.',
  payment_order_date: 'Date the payment order (CO7) was issued.',
  payment_advice_date: 'Date IREPS advised the bank to pay. Compared with the credit’s value date.',
  recovery_count: 'Number of recovery lines deducted from the bill.',
  recoveries: 'Recovery lines deducted from the bill.',
  return_reason: 'Why IREPS returned the bill, if it did.',
  net_check: 'Gross minus deductions equals net payable.',
  recovery_check: 'Recovery lines add up to the deducted amount.',
  operating_unit: 'Wabtec unit the bill belongs to, from the party code.',
  org_unit: 'Railway organisation unit that processed the bill.',
  data_row: 'Row of the bill in the IREPS export.',
  LineageStatus: 'Upstream documents (receipt note, CRN) linked to the bill.',
  PO: 'Purchase order the bill traces back to.',
  PO_Date: 'Date of the purchase order.',
  Receipt_Doc: 'Receipt note or CRN recording delivery.',
  Receipt_Date: 'Date of the receipt note or CRN.',
  DRR_or_Challan: 'Delivery receipt or challan number.',
  Bill_Reg_No: 'Bill registration number.',
  ExpectedBasis: 'Why the bill was expected to be paid in this period.',
  Settled: 'Whether a credit in this statement settled the bill.',
  AttemptCount: 'Times the bill was submitted (returned bills are resubmitted).',

  // --- recoveries / lineage -------------------------------------------
  recovery_head: 'What was recovered (e.g. TDS, penalty).',
  recovery_amt: 'Amount recovered on this line.',
  recovery_text: 'Recovery text exactly as IREPS wrote it.',
  doc_type: 'Kind of upstream document (receipt note, CRN, …).',
  doc_no: 'Document number.',
  doc_date: 'Document date.',
  invoice_no: 'Invoice (bill) number the document refers to.',
  po_no: 'Purchase order number.',
  po_date: 'Purchase order date.',
  receipt_qty: 'Quantity received.',
  drr_or_challan_no: 'Delivery receipt or challan number.',
  bill_reg_no: 'Bill registration number.',

  // --- matching evidence ------------------------------------------------
  confidence: 'How strongly the signals support the match. HIGH locks automatically; the rest wait for review.',
  flag: 'Why the match needs review.',
  zone_check: 'Whether the bank and bill signals (zone) agree.',
  date_check: 'Whether the dates fall within the tolerance.',
  date_gap_days: 'Days between the credit and the bill date compared.',
  date_source: 'Which bill date was compared: the advice date, or the payment order date as a fallback.',
  n_candidates: 'Bills with the same amount as this credit.',
  tied_candidates: 'Bills tied at the top score.',
  DateGapDays: 'Days between this bill’s date and the credit. Smaller is closer.',
  DateSource: 'Which bill date was compared.',
  exception_type: 'Credit with no bill, or bill with no credit.',
  gap_type: 'Why the item has no counterpart.',
  ledger_status: 'Live decision state of the match.',

  // --- table headers that are not data columns --------------------------
  'ui:when': 'When the match was created.',
  'ui:match': 'Durable match number.',
  'ui:run': 'Reconciliation run that created the row.',
  'ui:status': 'Open = awaiting a decision; Locked = settled; Rejected = released.',
  'ui:credit': 'The bank credit: amount, reference, value date and zone.',
  'ui:bills': 'The bill(s) settling the credit. +N = other bills with the same amount.',
  'ui:decision': 'Accept, reject or unlock. Add a note with “+ note”.',
  'ui:decided_by': 'Who made the latest decision. System = automatic.',
  'ui:exc_status': 'Open = still needs work; Resolved = closed by a match or a decision.',
  'ui:reference': 'Bank reference for a credit; bill number for a bill.',
  'ui:date': 'Credit value date, or the bill’s due date.',
  'ui:gap': 'Why the item has no counterpart yet.',
  'ui:segment': 'Business segment of the zone (e.g. TSG, OE). Set in Settings › Zones.',
  'ui:bill_status': 'Current IREPS status of the same-amount bill the credit is waiting on.',
  'ui:first_seen': 'Run that first reported the exception.',
  'ui:resolved_by': 'How the exception was closed, and by whom.',
  'ui:narrative': 'Free text the bank printed with the credit.',
  'ui:ar_status': 'Settled, in review, or outstanding.',
  'ui:ar_due': 'Due date: payment advice, else payment order, else submission date.',
  'ui:ar_paid_by': 'The bank credit that paid the bill.',
  'ui:ar_paid': 'Amount of that credit.',
  'ui:ar_variance': 'Credit minus net payable. For an outstanding bill, the full amount still owed.',
  'ui:ar_age': 'Days since the bill fell due (advice, else payment order, else submission date).',
  'ui:audit_when': 'When the event happened.',
  'ui:audit_user': 'Signed-in user who made the change. System = automatic.',
  'ui:audit_category': 'Kind of event.',
  'ui:audit_event': 'What happened.',
  'ui:audit_record': 'The record the event concerns.',
  'ui:audit_severity': 'Info, warning or error.',
}

/** The tooltip for a column, or undefined when none is written. */
export const helpFor = (key: string): string | undefined => COLUMN_HELP[key]
